set nocompatible

call plug#begin()

Plug 'sheerun/vim-polyglot'
Plug 'phelipetls/vim-hugo'

call plug#end()

let g:hugo_disable_indent = 1
autocmd BufNewFile,BufRead *.html set filetype=html
autocmd FileType htmlhugo setlocal indentexpr=HtmlIndent()
autocmd FileType htmlhugo setlocal syntax=html

set autoindent

set smartindent

set wrap

set hidden

set ttyfast

set showcmd

set modelines=0

set termguicolors

set t_Co=16

set cursorline "Show cursor highligh"

set showmode "Show mode"
 
set relativenumber "Show line number"

set ruler "Show file stats"

set visualbell "Blink cursor instead of beep"

set encoding=utf-8

set laststatus=2 "Show status line"

set showmatch "Show matching parenthese"

set incsearch "Search as character are entered"

set hlsearch "Show mathc"

set ignorecase "Search are case sensitive"

set clipboard=unnamedplus

colorscheme solarized8_flat

set background=dark
